name: farmabi-debezium

services:
  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    container_name: farmabi-debezium-zookeeper
    restart: unless-stopped
    ports:
      - "52181:2181"
    networks:
      - farmabi-net

  kafka:
    image: debezium/kafka:2.7.3.Final
    container_name: farmabi-debezium-kafka
    restart: unless-stopped
    ports:
      - "59092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - farmabi-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: farmabi-debezium-kafka-ui
    restart: unless-stopped
    ports:
      - "58085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: farmabi-debezium
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - farmabi-net

  connect:
    image: debezium/connect:2.7.3.Final
    container_name: farmabi-debezium-connect
    restart: unless-stopped
    ports:
      - "58083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
      STATUS_STORAGE_TOPIC: "connect_statuses"
    depends_on:
      - kafka
    networks:
      - farmabi-net

networks:
  farmabi-net:
    external: true
    name: farmabi-net

