farmabi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: farmabi-dw-pg
      user: postgres
      password: postgres
      port: 5432
      dbname: farmabi_dw
      schema: marts
      threads: 1
