name: 'farmabi'
version: '1.0.0'
config-version: 2

profile: 'farmabi'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  farmabi:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
