name: farmabi-dw

services:
  postgres-farmabi-dw:
    image: postgres:16-alpine
    container_name: farmabi-dw-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmabi_dw
      TZ: America/Lima
    ports:
      - "55432:5432"
    volumes:
      - farmabi_dw_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - farmabi-net

volumes:
  farmabi_dw_data:

networks:
  farmabi-net:
    external: true
    name: farmabi-net
